spring:
  application:
    name: spatial-data-streaming-poc
  profiles:
    active: local
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

scan:
  base-dir: /data/farm/uploads
  queue-capacity: 100
  partition:
    x-min: -5.0
    z-min: -5.0
    step: 0.25
    grid-count: 40

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
